name: 'GitOps Update'
description: 'Updates a key in a gitops repository and commit it'
inputs:
  filename: 
    description: 'Filename to update'
    required: true
  key:  
    description: "The key to update. Key a string before the colon. Usually it's yaml key like `this-is-key: value`"
    required: true
  value:  
    description: "The value to set"
    required: true
  github-deploy-key:  
    description: "Github deploy ssh private key to clone and commit target repository"
    required: true
  github-org-and-repo:  
    description: "Target organization and repository in form of `some-org/repo`"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        cache: pip
    - run: pip install -r requirements.txt
      shell: bash
    - run: ${{ github.action_path }}/run.sh "${{ inputs.filename }}" "${{ inputs.key }}" "${{ inputs.value }}" "${{ inputs.github-deploy-key }}" "${{ inputs.github-org-and-repo }}"
      shell: bash
